--- 
- name: Create environment ssh key within tower 
  hosts: localhost 
  connection: local 
  gather_facts: false 
  become: true 
  vars_files: 
    - /etc/openstack/clouds.yaml 
  vars: 
    guid: "{{ lookup('env', 'GUID') }}" 
    env_key: "{{ lookup('file', '/home/devops/.ssh/' + guid + 'key.pem') }}" 
    tower_auth_creds: 
      host: "https://control.{{ guid }}.dynamic.opentlc.com:8443" 
      username: "admin" 
      password: "r3dh4t1!" 
      ssl: "False" 
    tower_creds: 
      - name: "osp_environment_key" 
        type: "Machine" 
        org: "Default" 
        inputs: 
          ssh_key_data: "{{ env_key }}" 
          become_method: "sudo" 
          username: "cloud-user" 
   
      - name: "osp_cloud_creds" 
        type: "OpenStack" 
        org: "Default" 
        inputs: 
          username: "{{ vars['clouds'][guid ~ '-project']['auth']['username']         }}" 
          password: "{{ vars['clouds'][guid ~ '-project']['auth']['password']         }}" 
          host:     "{{ vars['clouds'][guid ~ '-project']['auth']['auth_url']         }}" 
          project:  "{{ vars['clouds'][guid ~ '-project']['auth']['project_name']     }}" 
          domain:   "{{ vars['clouds'][guid ~ '-project']['auth']['user_domain_name'] }}" 
   
  tasks: 
    - name: Add Credentials 
      awx.awx.tower_credential: 
        name:             "{{ __tower_creds.name        }}" 
        credential_type:  "{{ __tower_creds.type        }}" 
        organization:     "{{ __tower_creds.org         }}" 
        tower_host:       "{{ tower_auth_creds.host     }}" 
        tower_username:   "{{ tower_auth_creds.username }}" 
        tower_password:   "{{ tower_auth_creds.password }}" 
        validate_certs:   "{{ tower_auth_creds.ssl      }}" 
        inputs:           "{{ __tower_creds.inputs      }}" 
      loop: "{{ tower_creds }}" 
      loop_control: 
        loop_var: __tower_creds 
